FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

COPY AutoScallingTesterClient.csproj .
RUN dotnet restore AutoScallingTesterClient.csproj
# Copy everything
COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet","AutoScallingTesterClient.dll"]
CMD [ "http://localhost:8486" ]